### ISSUE TITLE
will this effect webpage performance ?

### ISSUE THREAD

**Issue by Anenth** [tholman/dom-animator#2]

**Comment by tholman** [comment]
Super awesome question. I haven't ran any real tests... the timeout is running once every second (which shouldn't cost much)

And the comment nodes changing should cause any redraws, or reflows... so I want to say no, but can't for sure.

**Comment by Anenth** [comment]
there isn't any redraws. So i guess its fine

**Comment by tholman** [comment]
Yep, its all good!
