### ISSUE TITLE
The demo is not friendly to Firefox

### ISSUE THREAD

**Issue by stof** [tholman/dom-animator#4]
The demo does not work in Firefox (which is expected as it does not support shadowDom yet), but the video does not work either (unsupported format). It would be great to provide a working video

**Comment by tholman** [comment]
The demo does work in firefox for me... no reason it shouldn't, since its all comments in the markup.
Video works here too (was under the impression firefox supports mp4's now, if they're encoded right).

Which firefox version/os are you using?

**Comment by stof** [comment]
OK, the issue for the demo is that I was using the Firebug inspector, not the builtin inspector. I can see the demo working in the builtin inspector.
Firebug 2 does not show comments by default. And when displaying them, it still does not refresh the comment when it gets updated (meaning we only see the first frame).

However, the video still does not work (same for your overscroll demo btw)
I'm using Firefox 37 on Ubuntu 14.04

**Comment by tholman** [comment]
Sweet. Thanks for the info, will see what I can do.

**Comment by tholman** [comment]
Old. Closing.
