### ISSUE TITLE
Firefox and Interner Explorer

### ISSUE THREAD

**Issue by Szymon-dziewonski** [tholman/dom-animator#8]
Hey, looks like animated comments are disabled in Firefox at all and in IE stops on last frame:/
But anyway thank you for great job :)!

**Comment by tholman** [comment]
Well, just checked this in firefox and it was fine... can't really see any reason why IE would break either.

**Comment by Szymon-dziewonski** [comment]
Hey, I tried this already in 5 computers (2x win 10, 3x and win 7 - in my work)
Here's screenshot from my personal 
Firefox (stops also - I havent got enabled comments) but still doesnt animate

![image](https://cloud.githubusercontent.com/assets/2566152/16034931/aa2126da-3214-11e6-86da-65bd7625227c.png)

nothings really happen

EDGE
![image](https://cloud.githubusercontent.com/assets/2566152/16034691/6871a3a0-3213-11e6-9cb2-3ceaf5bbe173.png)
or 
![image](https://cloud.githubusercontent.com/assets/2566152/16034864/5dd38200-3214-11e6-9f06-cfb5ed71d35b.png)

depends if I refresh with developer tools open or open after load page

IE
![image](https://cloud.githubusercontent.com/assets/2566152/16034803/073c86bc-3214-11e6-9f1c-a4b3bf19002b.png)
break on second frame

so yeah I'm still standing on this - that it is doesnt work everywhere beside Chrome and Opera

cheers

**Comment by tholman** [comment]
:(

Welp, don't really have IE/Edge so its probably not going to be fixed any time soon. Looks like firefox might work with the natural dev tools (at least on mac) but not with firebug.

Weird really, I guess it makes sense that the dev tools don't update comments after they're changed with code.

**Comment by Szymon-dziewonski** [comment]
yep same here, my friends told me about it and I test it. Wanted you to know :). Anyway nice piece of work and well fu*\* IE we all know that :)

**Comment by tholman** [comment]
Firefox looking good. Same with edge 🙏
